### ISSUE TITLE
Ability to embed spec file

### ISSUE THREAD

**Issue by retr0h** [alexferl/echo-openapi#8]
Any chance you would be open to supporting an API spec which is embedded?  Would simplify the distribution of code to users w/o them needing a current api spec.

```golang
import (
    "embed"
    mw "github.com/alexferl/echo-openapi"
    "github.com/labstack/echo/v4"
    "log"
)

//go:embed internal/api/gen/api.yaml
var apiSpec []byte

func main() {
    e := echo.New()

    e.Use(mw.OpenAPIFromBytes(apiSpec))
}


```

**Comment by alexferl** [comment]
Released in [v1.2.0](https://github.com/alexferl/echo-openapi/releases/tag/v1.2.0).
